server:
  port: 8080
  servlet:
    context-path: /pod

spring:
  datasource:
    url: "jdbc:mysql://poddatabase-2024-yugivip277-74b4.h.aivencloud.com:11566/podDatabase"
    username: avnadmin
    password: AVNS_H3_-kR4OTyfuUpf-_bo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
